# Generated by Django 3.1.3 on 2021-04-26 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_uuid_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid_channel',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID '),
        ),
    ]
