# Generated by Django 3.1.3 on 2021-04-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('acess_in', models.DateTimeField(auto_now_add=True, verbose_name='Acessado em')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
