# Generated by Django 3.1.3 on 2021-04-25 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='create_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='send_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notification_send', to='accounts.user', verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
