# Generated by Django 3.1.3 on 2021-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20210425_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='tipo_servico',
            field=models.IntegerField(choices=[('link', 'Link'), ('friendships', 'Friendships'), ('workspace', 'Workspace')], default=1),
            preserve_default=False,
        ),
    ]
