# Generated by Django 3.1.3 on 2021-07-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_auto_20210707_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
