# Generated by Django 3.1.3 on 2021-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_links_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkshared',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
